name: Linter

on:
  push:
    branches-ignore: [master, main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master, main]
jobs:
  build:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install NPM Packages
        run: npm ci
      - name: Lint Projects
        run: npm run lint
